### ISSUE TITLE
Buttons don't work? 

### ISSUE THREAD

**Issue by xChickens** [Supuhstar/Rent-Split-Calculator#89]
Hi, really cool web app! However, I've been trying to use it on my Android phone and I can't seem to press any of the buttons. I've tried both Chrome and Firefox, both portrait and landscape, and both mobile mode and desktop mode and I can't seem to add any new roommates nor click the save data buttons (the save data buttons show an animation but nothing seems to happen/they don't disappear)

Wondering if this is a me problem or mobile isn't supported? Thanks.

**Comment by xChickens** [comment]
Actually I just tested on desktop and the buttons still don't work. Is the functionality not actually working?

**Comment by KyNorthstar** [comment]
Hmmm... they work fine for me. 

Just now I tried using:
- Firefox on macOS
- Vivaldi on macOS
- Safari on macOS
- Firefox on iOS
- Chrome on Android

Perhaps you have a script blocker enabled? If so, then yeah this web app won't work without scripting, so you'll have to turn it off in order to use it.

Though... I highly doubt that's the case, since (I just remembered), when you block all JS from running, you get this:
![CleanShot 2023-07-17 at 19 31 41@2x](https://github.com/BlueHuskyStudios/Rent-Split/assets/10189808/ce950877-3adf-455d-8d92-8ccc450b24a8)

If you have a script blocker running and that's not showing up, then that's an edge case that I want to fix. If so, please let me know which one so I can test on my side and make sure that warning pops up if it's blocking my scripts.

**Could you tell me whether you're using a script-blocking browser extension, which versions of which browsers you used, and which versions of which OSs you used?**

**Comment by xChickens** [comment]
I didn't see the pop up and I was using Firefox on Windows, Firefox on Android, and Chrome on Android. I don't know why it didn't work before but it seems to be working completely fine now.

**Comment by KyNorthstar** [comment]
Glad it's working again! If this ever happens again feel free to bring it up here with the same kinda info and I'll dive into it
